//$TB_PATH/uvm_env/driver/xfi_drv.sv
//$TB_PATH/uvm_env/monitor/xfi_monitor.sv
//$TB_PATH/uvm_env/driver/tx_internal_drv.sv
//$TB_PATH/uvm_env/agent/xfi_agent.sv
//$TB_PATH/uvm_env/agent/tx_internal_agent.sv
//$TB_PATH/uvm_env/transaction/tx_internal.sv
//$TB_PATH/uvm_env/transaction/ohp_eth_pkt_ingress.sv
//$TB_PATH/uvm_env/transaction/ethernet_packet.sv
//$TB_PATH/uvm_env/sequence/xfi_seq.sv
//$TB_PATH/uvm_env/sequence/xfi_sequencer.sv
//$TB_PATH/uvm_env/interface/tx_internal_if.sv
//$TB_PATH/uvm_env/interface/clinkh32_if.sv

$TB_PATH/uvm_env/driver/igmii_drv.sv
$TB_PATH/uvm_env/driver/xgmii_drv.sv
$TB_PATH/uvm_env/driver/cpu_fifo_drv.sv
$TB_PATH/uvm_env/monitor/igmii_monitor.sv
$TB_PATH/uvm_env/monitor/xgmii_monitor.sv
$TB_PATH/uvm_env/monitor/cpu_fifo_monitor.sv
$TB_PATH/uvm_env/env/falcon_env.sv
$TB_PATH/uvm_env/agent/igmii_agent.sv
$TB_PATH/uvm_env/agent/xgmii_agent.sv
$TB_PATH/uvm_env/agent/cpu_fifo_agent.sv
$TB_PATH/uvm_env/base_test/falcon_test.sv
$TB_PATH/uvm_env/transaction/gcc_packet.sv
$TB_PATH/uvm_env/transaction/ohb_eth_packet.sv
$TB_PATH/uvm_env/scoreboard/falcon_scb.sv
$TB_PATH/uvm_env/sequence/igmii_seq.sv
$TB_PATH/uvm_env/sequence/igmii_sequencer.sv
$TB_PATH/uvm_env/sequence/xgmii_seq.sv
$TB_PATH/uvm_env/sequence/xgmii_sequencer.sv
$TB_PATH/uvm_env/sequence/cpu_fifo_seq.sv
$TB_PATH/uvm_env/sequence/cpu_fifo_sequencer.sv
$TB_PATH/uvm_env/interface/mac_10g_if.sv
$TB_PATH/uvm_env/interface/igmii_if.sv
$TB_PATH/uvm_env/interface/xgmii_if.sv
$TB_PATH/uvm_env/interface/axi_lite_if.sv

$TB_PATH/verification/common/flow_control.sv
$TB_PATH/verification/common/timer.sv
$TB_PATH/verification/packets/hdlc_packet.sv
$TB_PATH/verification/packets/hdlc_channel.sv
$TB_PATH/verification/stimulation/xgmii_stim.sv
$TB_PATH/verification/stimulation/igmii_stim.sv
$TB_PATH/verification/stimulation/exp_stim.sv
$TB_PATH/verification/registers/modReg.sv
$TB_PATH/verification/registers/myFileLine.sv
$TB_PATH/verification/registers/myString.sv
$TB_PATH/verification/registers/readLabCtrl.sv
$TB_PATH/verification/registers/register.sv
$TB_PATH/verification/registers/regReadWrite.sv
$TB_PATH/verification/testcase/testcase.sv
$TB_PATH/verification/testcase/test_chnl.sv
$TB_PATH/verification/checker/gcc_pkt_check.sv
$TB_PATH/verification/checker/hdlc_pkt_check.sv

//$TB_PATH/verification/testcase/svf_fixed_chnl_data_only.sv
//$TB_PATH/verification/testcase/svf_rand_chnl_data_only.sv
//$TB_PATH/verification/testcase/svf_fixed_chnl_req_only.sv
//$TB_PATH/verification/testcase/svf_rand_chnl_req_only.sv
//$TB_PATH/verification/testcase/svf_fixed_chnl_req_data.sv
//$TB_PATH/verification/testcase/svf_rand_chnl_req_data.sv
//$TB_PATH/verification/testcase/svf_aps_multi_chnl.sv
//$TB_PATH/verification/testcase/svf_aps_sanity.sv
