+incdir+$FALCON_ROOT/rtl/gcc_proc/common/

$FALCON_ROOT/rtl/gcc_proc/packet_capture.v
$FALCON_ROOT/rtl/testcase/crc_gen.v
$FALCON_ROOT/rtl/testcase/crc_chk.v
$FALCON_ROOT/rtl/gcc_proc/common/mydelay_m_v2.v
$FALCON_ROOT/rtl/gcc_proc/common/My_DPRAM.v
$FALCON_ROOT/rtl/gcc_proc/common/MyFIFO16xN_M.v
$FALCON_ROOT/rtl/gcc_proc/common/MyFIFO_Ctrl_M.v
$FALCON_ROOT/rtl/gcc_proc/common/MyLib_1v1.v
$FALCON_ROOT/rtl/gcc_proc/common/my_sdpram_e.v
$FALCON_ROOT/rtl/gcc_proc/common/My_SDPRAM.v
$FALCON_ROOT/rtl/gcc_proc/common/My_SDPRAM_V2.v
$FALCON_ROOT/rtl/gcc_proc/common/my_stpram.v
$FALCON_ROOT/rtl/gcc_proc/common/Nbit_DelayM_E.v
$FALCON_ROOT/rtl/gcc_proc/common/Nbit_DelayM.v
$FALCON_ROOT/rtl/gcc_proc/common/PPEXTD_Lib.v
$FALCON_ROOT/rtl/gcc_proc/common/rx_muti_hdlc_ctrl.v
$FALCON_ROOT/rtl/gcc_proc/common/Syn_FIFO.v
$FALCON_ROOT/rtl/gcc_proc/common/syn_packet_chnfifo.v
$FALCON_ROOT/rtl/gcc_proc/common/syn_packet_fifo.v
$FALCON_ROOT/rtl/gcc_proc/common/packet_len_detect.v
$FALCON_ROOT/rtl/gcc_proc/common/top_muti-hdlc.v
$FALCON_ROOT/rtl/gcc_proc/common/tx_muti_hdlc_ctrl.v
$FALCON_ROOT/rtl/gcc_proc/common/history_alarm_proc.v
$FALCON_ROOT/rtl/gcc_proc/emac/asyn_fsm.v
$FALCON_ROOT/rtl/gcc_proc/emac/Client_Loopback.v
$FALCON_ROOT/rtl/gcc_proc/emac/crc32_d32_m4.v
$FALCON_ROOT/rtl/gcc_proc/emac/CRC32_D8.v
$FALCON_ROOT/rtl/gcc_proc/emac/emac_core_top.v
$FALCON_ROOT/rtl/gcc_proc/emac/mod_add.v
$FALCON_ROOT/rtl/gcc_proc/emac/rx_check.v
$FALCON_ROOT/rtl/gcc_proc/emac/rx_delay_1_turn.v
$FALCON_ROOT/rtl/gcc_proc/emac/rx_gen_fcs.v
$FALCON_ROOT/rtl/gcc_proc/emac/rx_module.v
$FALCON_ROOT/rtl/gcc_proc/emac/rx_pause_tx.v
$FALCON_ROOT/rtl/gcc_proc/emac/rx_rm_header.v
$FALCON_ROOT/rtl/gcc_proc/emac/rx_sfd_proc.v
$FALCON_ROOT/rtl/gcc_proc/emac/tx_append_fcs.v
$FALCON_ROOT/rtl/gcc_proc/emac/tx_data_frame.v
$FALCON_ROOT/rtl/gcc_proc/emac/tx_frame_gap.v
$FALCON_ROOT/rtl/gcc_proc/emac/tx_fsm.v
$FALCON_ROOT/rtl/gcc_proc/emac/tx_module.v
$FALCON_ROOT/rtl/gcc_proc/emac/tx_pause_frame.v
$FALCON_ROOT/rtl/gcc_proc/emac/tx_stats.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/gcc_mapper_proc.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/mii_to_mac.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/sram_hdlc_tx_if.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/sram_rd_ctrl_proc.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/sram_wr_ctrl_proc.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/sram_wr_rd_ctrl.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/sram_wr_rd_info_proc.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/rx_mac_data_checker_fix_chn_cfg.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/mactohdlc_mcu_fix_chn_cfg.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/mac_tohdlc_top_fix_chn_cfg.v
$FALCON_ROOT/rtl/gcc_proc/mcu/gcc_ctrl.v
$FALCON_ROOT/rtl/gcc_proc/mcu/gcc_mcu_top.v
$FALCON_ROOT/rtl/gcc_proc/misc/gcc_bram_io_proc.v
$FALCON_ROOT/rtl/gcc_proc/misc/my_loopback.v
$FALCON_ROOT/rtl/gcc_proc/misc/rd_clr_counter.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/gcc_demapper_proc.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/hdlc_rx_fifo_if.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/hdlctomac_mcu.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/hdlc_tomac_top.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/mactomii.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/mac_tx_if.v
$FALCON_ROOT/rtl/gcc_proc/mac_oh_top.v
$FALCON_ROOT/rtl/gcc_proc/top_gcc_proc.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/gcc_demapper_proc_otu4.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/hdlc_rx_fifo_if_otu4.v
$FALCON_ROOT/rtl/gcc_proc/oh_to_mac/hdlc_tomac_top_otu4.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/gcc_mapper_proc_otu4.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/mac_tohdlc_top_otu4.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/rx_mac_data_checker_otu4.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/sram_wr_rd_ctrl_otu4.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/sram_wr_rd_info_proc_otu4.v
$FALCON_ROOT/rtl/gcc_proc/mac_to_oh/sram_hdlc_tx_if_otu4.v
$FALCON_ROOT/rtl/gcc_proc/misc/my_loopback_otu4.v
$FALCON_ROOT/rtl/gcc_proc/mac_oh_top_otu4.v
$FALCON_ROOT/rtl/gcc_proc/top_gcc_proc_otu4.v
